apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-dashboards
  annotations:
    github.com/project-slug: hacky-stuff/new-dashboards
spec:
  type: other
  lifecycle: unknown
  owner: user:default/guest
