apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: github-issues-log-sink
spec:
  source:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: github-issues
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink
    properties:
      showHeaders: true
      showStreams: true
